# ./docker/php/Dockerfile
FROM php:7.4-fpm

RUN docker-php-ext-install pdo_mysql 


RUN apt-get update && \
apt-get install -y \
libzip-dev \
&& pecl install xdebug redis \
&& docker-php-ext-enable xdebug redis 

RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" \
	php -r "if (hash_file('sha384', 'composer-setup.php') === 'e5325b19b381bfd88ce90a5ddb7823406b2a38cff6bb704b0acc289a09c8128d4a8ce2bbafcd1fcbdc38666422fe2806') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;" \
	&& php composer-setup.php \
	&& php -r "unlink('composer-setup.php');" \
	&& mv composer.phar /usr/local/bin/composer
 
WORKDIR /usr/src/app
COPY pastaTask/ /usr/src/app/
COPY docker/php/start.sh /opt/start.sh
RUN chmod 551 /opt/start.sh && chown -R www-data:www-data var
RUN PATH=$PATH:/usr/src/app/vendor/bin:bin
EXPOSE 9000
CMD /opt/start.sh
