version: '3.8'
services:
  mysql:
    image: mysql:8.0.19
    restart: unless-stopped
    environment:
      - "MYSQL_USER=pasta" 
      - "MYSQL_PASSWORD=s0LongPassw0rd"
      - "MYSQL_ROOT_PASSWORD=Y0uw1llN3verGuessitImHav1ngFunFwoRd"
      - "MYSQL_DATABASE=pasta"
      - "MYSQL_ROOT_HOST=%"
#    volumes:
#      - "./data/:/var/lib/mysql"
#    networks:
#      - web1
    command:
      - "--default-authentication-plugin=mysql_native_password"
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    restart: unless-stopped
    volumes:
      - './pastaTask:/usr/src/app'
      - './docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf'
    depends_on:
      - mysql
#    networks:
#      - web1
  nginx:
    image: nginx:1.19.0-alpine
    restart: unless-stopped
    volumes:
      - './pastaTask/public/:/usr/src/app'
      - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
    ports:
      - '0.0.0.0:80:80'    
    depends_on:
      - php
      - redis
#    networks:
#      - web1 
  redis:
    image: redis
    restart: unless-stopped
#    networks:
#     - web1

  api:
    build:
      context: .
      dockerfile: docker/bot/Dockerfile
    volumes:
      - "./BotApi:/opt/initializer/app"
    restart: unless-stopped

#networks:
#  web1:
#    driver: bridge
